language: python

env:
  - PYTHON="2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - npm install
  - npm install grunt-coveralls --save-dev
  - node_modules/bower/bin/bower install
  - gem install coveralls-lcov

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo "SECRET_KEY = 'key-for-testing'" > instance/config.py

script:
  - nosetests --with-coverage --cover-package=wqp
  - node_modules/karma/bin/karma start test/js/karma.conf.js --no-colors

after_success:
  coveralls-lcov -v -n "coverage/Firefox 31.0.0 (Linux 0.0.0)/lcov.info" > "coverage/Firefox 31.0.0 (Linux 0.0.0)/coverage.json";
  ls -al "coverage/Firefox 31.0.0 (Linux 0.0.0)";
  coveralls --merge="coverage/Firefox 31.0.0 (Linux 0.0.0)/coverage.json";
