language: python

env:
  - PYTHON="2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - npm install
  - node_modules/bower/bin/bower install
  - gem install coveralls-lcov

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo "SECRET_KEY = 'key-for-testing'" > instance/config.py

script:
  - nosetests --logging-clear-handlers --with-coverage --cover-package=wqp
  - node_modules/karma/bin/karma start test/js/karma.conf.js --no-colors

after_success:
  find coverage/ -mindepth 2 -iname '*.info' -exec cp -t coverage/ '{}' +;
  coveralls-lcov -v -n coverage/lcov.info > coverage/coverage.json;
  coveralls --merge=coverage/coverage.json;
