language: python

env:
  - PYTHON="3.6"

before_install:
  - nvm install 6.10.2

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - npm install
  - gem install coveralls-lcov

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo "SECRET_KEY = 'key-for-testing'" > instance/config.py

script:
  - coverage run --omit=*/tests*.py,/home/travis/virtualenv/* -m unittest

after_success:
  coveralls
