# These overrides are for continuous integration systems. Usage example:
# docker-compose -f docker-compose.yml -f docker-compose.ci.yml run assets

version: "3"

services:
  assets:
    command: npm test
    volumes:
      - ./coverage/assets:/assets/coverage
  server:
    volumes:
      - ./coverage/server:/server/coverage
      - ./server/instance:/server/instance
    command: make test
